"""init schema

Revision ID: 006e7d995c28
Revises: 
Create Date: 2025-11-06 20:50:43.120315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '006e7d995c28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_auth_id'), 'auth', ['id'], unique=False)
    op.drop_constraint('auth_user_id_fkey', 'auth', type_='foreignkey')
    op.create_foreign_key(None, 'auth', 'users', ['user_id'], ['id'])
    # Backfill created_at before making it NOT NULL to avoid integrity errors
    op.execute("UPDATE notifications SET created_at = now() WHERE created_at IS NULL")
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_notifications_unread', table_name='notifications')
    op.drop_index('idx_notifications_user_unread', table_name='notifications')
    op.drop_column('notifications', 'delivered_at')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_users_name', table_name='users')
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('notifications', sa.Column('delivered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('idx_notifications_user_unread', 'notifications', ['receiver_id', 'is_read', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_notifications_unread', 'notifications', ['receiver_id', 'is_read', 'created_at'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'auth', type_='foreignkey')
    op.create_foreign_key('auth_user_id_fkey', 'auth', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_auth_id'), table_name='auth')
    # ### end Alembic commands ###
